import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta 
        name="viewport"
        content="width=device-width, height=device-height, initial-scale=1"
        />
      </head>
      <body className={inter.className}><div>
        <Header/>
        <main className="pt-navigation-height bg-page-gradient">{children}</main>
        <Footer/>
      </div></body>
    </html>
  );
}
